idf_component_register(
    SRCS
        "main.c"
        "kiss.c"
        "transport.c"
        "transport_wifi.c"
        "LibAPRS-esp32-i2s/src/LibAPRS.cpp"
        "LibAPRS-esp32-i2s/src/AFSK.cpp"
        "LibAPRS-esp32-i2s/src/AX25.cpp"
        "LibAPRS-esp32-i2s/src/CRC-CCIT.c"
        "ptt.c"
        "aux_file_management.c"
        "aux_config.c"
        "audio_stream.c"
    INCLUDE_DIRS
        "."
        "LibAPRS-esp32-i2s"
        "LibAPRS-esp32-i2s/src/"
    REQUIRES
        esp_wifi
        nvs_flash
        esp_netif
        lwip
        driver
        esp_driver_dac
        esp_driver_gpio
        esp_adc
        spiffs
        esp_http_server
        vfs
)
spiffs_create_partition_image(
    spiffs
    spiffs_data
    FLASH_IN_PROJECT
)
